name:  GCP Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - name: Get ssh key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy to AWS
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dist/* ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.DEPLOY_DIR }}
      - name: Restart Server
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} "bash -lc 'cd ${{ secrets.DEPLOY_DIR }} && npm install && if pm2 describe cloud-learn > /dev/null 2>&1; then pm2 restart cloud-learn; else pm2 start npm --name cloud-learn -- start; fi && pm2 save'"